# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent
service:
  name: property-vision-api
  notes_workaround: FAKE
  internalPort: 8080
resources:
  limits:
    cpu: 0.9
    memory: 512Mi
  requests:
    cpu: 0.9
    memory: 512Mi
probePath: /_mgmt/health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10