# Default values for python.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
forceNodeType: gpu # matches the spotinst elastigroup node label
image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent
service:
  name: REPLACE_ME_APP_NAME
  internalPort: 8000
  livenessProbe:
    path: /_mgmt/health
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    path: /_mgmt/health
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 1
    failureThreshold: 3
resources:
  # corresponds to allocating most of p2.xlarge capacity
  # https://ec2instances.info/?filter=p2.xlarge
  limits:
    cpu: 3
    memory: 54G
    nvidia.com/gpu: 1
  requests:
    cpu: 3
    memory: 54G
    nvidia.com/gpu: 1
env:
  production:
    - name: foo
      value: bar
  development:
    - name: foo
      value: bar
