apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.name }}
  name: {{ .Values.service.name }}
  {{- else }}
  name: {{ template "fullname" . }}
  {{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
    - port: 8501
      targetPort: 8051
      name: rest
    - port: 8500
      targetPort: 8500
      name: grpc
  selector:
    app: {{ template "fullname" . }}
