pipeline {
  agent {
    label "jenkins-python"
  }
  environment {
    ORG = 'REPLACE_ME_ORG'
    APP_NAME = 'REPLACE_ME_APP_NAME'
    MODULE_NAME = "${APP_NAME.replaceAll(/-/, "_")}"
    PYPI_ADDRESS = credentials('pypi-address')
    PYPI_CREDS = credentials('pypi-credentials')
    TWINE_USERNAME = "${PYPI_CREDS_USR}"
    TWINE_PASSWORD = "${PYPI_CREDS_PSW}"
    TWINE_REPO = "https://${PYPI_ADDRESS}"
    PIP_EXTRA_INDEX_URL = "https://${PYPI_CREDS}@${PYPI_ADDRESS}/simple"
  }
  stages {
    stage('Unit test') {
      when {
        expression {
          return sh(script: "git log -1 --pretty=format:'%an' | grep '^jenkins-x-bot'", returnStatus: true) != 0
        }
      }
      steps {
        container('python') {
          sh """
          docker build \
            --build-arg app_name=${APP_NAME} \
            --build-arg environment=development \
            --build-arg artifactory_url=${PIP_EXTRA_INDEX_URL} \
            -t test-image:latest .
          """
          sh "docker run --rm test-image:latest pytest -v --cov=${MODULE_NAME}"
        }
      }
    }
    stage('Build and publish PR') {
      when {
        branch 'PR-*'
      }
      steps {
        container('python') {
          script {
            base_version = readFile('VERSION').trim()
            pr = BRANCH_NAME.replaceAll(/-/, "").toLowerCase()
            expanded_version = "${base_version}.dev0+${pr}.${BUILD_NUMBER}"
            writeFile(file: 'VERSION', text: expanded_version.join('.'))

            sh "python3 setup.py bdist_wheel"
            sh "twine upload --repository-url ${TWINE_REPO} dist/*"

            pullRequest.comment("Successfully built and published **$expanded_version**")
          }
        }
      }
    }
    stage('Build and publish "master"') {
      when {
        expression {
          return BRANCH_NAME == 'master' && sh(script: "git log -1 --pretty=format:'%an' | grep '^jenkins-x-bot'", returnStatus: true) != 0
        }
      }
      steps {
        container('python') {
          script {
            sh "python3 setup.py bdist_wheel"
            sh "twine upload --repository-url ${TWINE_REPO} dist/*"

            version = readFile('VERSION').trim()
            sh "jx step git credentials"
            sh "git config credential.helper store"
            sh "git tag -fa v${version} -m 'Release version ${version}'"
            sh "git push origin v${version}"
          }
        }
      }
    }
    stage('Increment patch version') {
      when {
        expression {
          return BRANCH_NAME == 'master' && sh(script: "git log -1 --pretty=format:'%an' | grep '^jenkins-x-bot'", returnStatus: true) != 0
        }
      }
      steps {
        container('python') {
          script {
            sh "git checkout master"

            version = readFile('VERSION').trim().split(/\./)
            version[2] = ((version[2] as Integer) + 1) as String
            writeFile(file: 'VERSION', text: version.join('.'))

            sh "git add VERSION"
            sh "git commit -m 'Increment patch version'"
            sh "jx step git credentials"
            sh "git config credential.helper store"
            sh "git push"
          }
        }
      }
    }
  }
  post {
    always {
      cleanWs()
    }
  }
}
